### ISSUE TITLE
Can't use fonts

### ISSUE THREAD

**Issue by wilsonowilson** [nativeshell/nativeshell#87]
I can't seem to add a custom font to my project built with nativeshell. Trying to add a font to the pubspec.yaml causes the build to fail with this error:
```
Stderr:
  [  +67 ms] Error: unable to locate asset entry in pubspec.yaml: "fonts/Inter/Inter-Regular.ttf".
  [  +11 ms] Target debug_macos_bundle_flutter_assets failed: Exception: Failed to bundle asset files.
             #0      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:61:5)
```

I have confirmed the path to the asset is correct, and I have used the exact same configuration on another project to be sure.

**Comment by knopp** [comment]
This could definitely be issue with nativeshell build. Given that some flutter targets little the root project structure with ephemeral files as a workaround nativeshell runs the actual flutter build in a subfolder inside build folder. It does create symlinks for assets, but there might be cases where it doesn't work correctly. Is there a repository I can reproduce this with?

**Comment by wilsonowilson** [comment]
Not that I have publicly available, but I think trying to add a custom font to the nativeshell examples might produce the same error. I'll try and see immediately

**Comment by wilsonowilson** [comment]
Trying to add a custom font to the example project produces this error:
```
  Stderr:
  [        ] Unexpected child "example" found under "flutter".
  [   +8 ms] Please correct the pubspec.yaml file at /Users/wilson/Developer/Experimenting/examples/target/x86_64-apple-darwin/debug/build/nativeshell_examples-c92add7ebd1546ee/out/flutter/pubspec.yaml
  ```

**Comment by knopp** [comment]
That seems like a flutter tool error. Are you sure the pubspec.yaml is correct? Can you post it here?

**Comment by wilsonowilson** [comment]
My bad, the pubspec.yaml file was not correctly formatted. Trying again on the app template yielded the same error:

```
  Stderr:
  [  +50 ms] Error: unable to locate asset entry in pubspec.yaml: "fonts/Inter/Inter-Regular.ttf".
  [   +5 ms] Target debug_macos_bundle_flutter_assets failed: Exception: Failed to bundle asset files.
             #0      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:61:5)
```

**Comment by knopp** [comment]
Can you post the whole pubspec.yaml? Just in case. I'll try to reproduce this tomorrow.

**Comment by wilsonowilson** [comment]
Sure!
```yaml
name: app_template
description: NativeShell application template
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0-214.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.9.2
  path: ^1.7.0

  cupertino_icons: ^1.0.0
  nativeshell:
    version: ^0.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter/Inter-Regular.ttf
        - asset: fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter/Inter-Black.ttf
          weight: 900    
```

**Comment by wilsonowilson** [comment]
I can upload the project to a temporary repository if that helps

**Comment by wilsonowilson** [comment]
Here's the app template with fonts included: https://github.com/wilsonowilson/app_template

**Comment by knopp** [comment]
Sure, it won't harm :) Or at least the fonts folder. But I think the problem is that nativeshell only recognizes `flutter/assets`, it ignores flutter/fonts at this point. The functionality will need to be added in `flutter_build.rs` (`copy_pubspec_yaml`)

**Comment by wilsonowilson** [comment]
I initially tried with an assets folder. Let me update the example and see if that works.

**Comment by knopp** [comment]
I think for now you can manually add the fonts in `flutter/assets` so that they get copied.

**Comment by wilsonowilson** [comment]
In the flutter sdk?

**Comment by knopp** [comment]
No, I meant specifying the font files as flutter assets in pubspec.yaml (https://flutter.dev/docs/development/ui/assets-and-images)

**Comment by knopp** [comment]
Something like this should work:
```
flutter:
  assets:
    - fonts/
```

**Comment by wilsonowilson** [comment]
Ah, gotcha. I guess if I wanted to use fonts that way, I'd have to use the [FontLoader](https://api.flutter.dev/flutter/services/FontLoader-class.html), correct?

**Comment by wilsonowilson** [comment]
Oh I think I misunderstood. It just helps nativeshell create a link, right?

**Comment by knopp** [comment]
No, you should be able to have both in pubspec.yaml
```
flutter:
  uses-material-design: true
  assets:
    - fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter/Inter-Regular.ttf
        - asset: fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter/Inter-Black.ttf
          weight: 900    
```
I haven't test this but it should work. The `assets/fonts` part is there just so that nativeshell makes the proper symlink before running the build. 

In any case, this is a bug and it should be fixed properly.
